name: Puma Price Tracker

on:
  workflow_dispatch:

  schedule:
    - cron: "0 5 * * *"
    - cron: "16 12 * * *"
    - cron: "0 18 * * *"

jobs:
  check-prices:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run tracker
        run: python main.py
